version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "graph-sample/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
